#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
#POSTGRESQL_HOST: 192.168.4.57
POSTGRESQL_HOST: 10.178.172.88
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ravisankar231299@gmail.com
EMAIL_PASSWORD: egcz pkdy oxiz jsxi
VERIFY_EMAIL_HOST: http://localhost:5173

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}